### ISSUE TITLE
Gitter/Discord Channel For Communication

### ISSUE THREAD

**Issue by toksdotdev** [yever/rusty-typescript#29]
I'm willing to contribute in whatsoever way possible, although having a steady medium of communication could bridge the gap between new contributors and your existing road map.

**Comment by lulu-berlin** [comment]
Thank you so much! I'd love to have some support and help in this project.
Let me try to figure out how to start a communication channel for contributors.

**Comment by lulu-berlin** [comment]
Ok, I started this community in gitter: https://gitter.im/rusty-typescript/

Please join. I'll also add a link in the README.

**Comment by toksdotdev** [comment]
Just joined 👌

**Comment by lulu-berlin** [comment]
I started a discussion there. I'd be happy if you could join it, so we can plan how to continue.

**Comment by lulu-berlin** [comment]
I'm closing this issue now, since we have a gitter channel now.
